name: Safety

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2

      - name: Install necessary dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety poetry

      - name: Check for security issues
        run: poetry export -f requirements.txt | safety check --stdin
